### PR TITLE
Feat: Add 3D carousel & headers to home page

### PR DESCRIPTION
**Pull request by Tony9984**
Changes on this PR:

- Get songs dynamically from backend
- Implement 3D carousel library + preliminary styling
- Add desktop & mobile headers from main site (removed some routes since its an external app)
- Styling is subset to change! Let me know your thoughts!! :D

TODO:

- Adjust styling for mobile 3D carousel

Screenshots:

image

### CODE REVIEW

**Review by cxy2015ca — CHANGES_REQUESTED** [review]
looks very clean, the transition is very smooth!! There's a few warnings tho `index.js:1 Warning: Each child in a list should have a unique "key" prop`, can we resolve this before merging

**Comment by cxy2015ca** [comment]
one more thing, currently the rotate is onClick on the album cover, how do you plan to handle the redirect into Preview page, are we doing a separate button

**Comment by Tony9984** [comment]
got it! i'll fix the warning during the call. as for the rotate onClick, I have a way of resolving that issue, prob an onclick on the current album only, i'll explain a bit more during the call. thanks for the review!!

**Review by cxy2015ca — APPROVED** [review]
nice!

**Pull request merged**
